### ISSUE TITLE
Stuck when accessing the front-end page

### ISSUE THREAD

**Issue by woshihahaha** [paritytech/substrate-telemetry#401] opened 2021-09-16 09:22 UTC
1.Server System：Ubuntu-20.04
2.The firewall is enabled for all ports.
3.When accessing the front-end page, all services start normally. The startup log is as follows:
![image](https://user-images.githubusercontent.com/78835349/133586421-ff47b228-f56c-424b-9bf4-46768e19f4a2.png)
4.The Frontend Page cannot be opened.
![image](https://user-images.githubusercontent.com/78835349/133586664-6fac16bb-20d3-4a2a-8ef2-e6c268f390b2.png)

**Comment by dvdplm** [comment] 2021-09-16 11:26
Do you see any errors in the browser log? What command did you use to start the backend (core and backend)? What does your `nginx` config look like and are you positive that it is proxying websocket connections correctly?

**Comment by woshihahaha** [comment] 2021-09-16 11:43
Started with docker-compose, the configuration is as follows, the default configuration cannot connect to localhost, so I changed the localhost address to the server intranet ip address
![image](https://user-images.githubusercontent.com/78835349/133605656-01e3fbe8-5bdf-46e8-96c9-c8bb5f0bed06.png)
No error is found in the browser log.

**Comment by dvdplm** [comment] 2021-09-16 13:17
Can you reproduce the problem if you run the telemetry core, shard and front end without docker (and nginx)?

**Comment by woshihahaha** [comment] 2021-09-16 13:31
I have tried three methods of deployment, such as compilation and installation, docker installation, and docker-compose installation, all of which are the current problems.

**Comment by dvdplm** [comment] 2021-09-16 20:20
Is your polkadot node reporting any connection problems when it starts? 
For instance, if I don't run telemetry and then run my polkadot node like so:

```
./target/release/polkadot --dev --telemetry-url 'ws://127.0.0.1:8001/submit 0'
```

…then I see a connection error like this among the logs printed at startup:

```
2021-09-16 22:18:14 ❌ Error while dialing /ip4/127.0.0.1/tcp/8001/x-parity-ws/%2Fsubmit: Custom { kind: Other, error: Other(A(Handshake(Io(Os { code: 32, kind: BrokenPipe, message: "Broken pipe" })))) }
```

Do you see the node connect properly, i.e. do you **not** see an error message like above?

**Comment by woshihahaha** [comment] 2021-09-17 01:50
Run the polkadot node without starting telemetry：
![image](https://user-images.githubusercontent.com/78835349/133710678-9065ee2b-e9c2-467e-89f5-0e751a7f2501.png)
I didn't receive your mistake. The error I received was:
![image](https://user-images.githubusercontent.com/78835349/133710865-eaed18c7-43aa-4b0a-a11c-a9e6f2f8335b.png)

**Comment by woshihahaha** [comment] 2021-09-17 01:55
After starting telemetry, run the polkadot node again. It seems that Port 8001 of telemetry can be connected normally without receiving any error message.
![image](https://user-images.githubusercontent.com/78835349/133711344-a364efe9-daeb-4909-8812-3efc2847e86f.png)

**Comment by woshihahaha** [comment] 2021-09-17 02:10
If you connect to the address 'ws:// localhost:8000/feed', an error is returned:
![image](https://user-images.githubusercontent.com/78835349/133712787-9ff00a4c-cbeb-4384-9bb2-ea7e4e2f217c.png)
If you connect to an intranet IP address: 8000/feed or an Internet IP address: 8000/feed, the connection will be stuck without any error.

**Comment by dvdplm** [comment] 2021-09-17 11:52
Do you see anything in the logs for `telemetry_core`? Increase the log level with `--log debug`. 
Using `wscat -c ws://localhost:8000/feed` I see `[telemetry_core] Opening /feed connection from 127.0.0.1:61916`.

Not sure what you mean by "intranet IP address", can you elaborate?

To debug this it'd be good to start removing as many layers as possible and run everything on the same machine in different terminals, so no docker, nginx or other services involved.

**Comment by woshihahaha** [comment] 2021-09-17 14:19
Compile and install without debugging nginx or docker
Browser log error：
![image](https://user-images.githubusercontent.com/78835349/133797913-f1128993-83a3-4f72-b04f-8973674e11cf.png)
telemetry_core log error:
![image](https://user-images.githubusercontent.com/78835349/133798125-33d2034c-8924-411a-9f5c-6f64feb6a037.png)

**Comment by dvdplm** [comment] 2021-09-17 16:20
I am confused now, what does the first screenshot show? Can you try using just `wscat -c ws://localhost:8000/feed`?

**Comment by woshihahaha** [comment] 2021-09-17 17:13
![image](https://user-images.githubusercontent.com/78835349/133827509-b6fdcc53-143c-43b1-8dbe-0b1b7ffd7fe7.png)
![image](https://user-images.githubusercontent.com/78835349/133827776-bd90bbc7-b2b5-49cd-bdf6-30c2542f2900.png)
telemetry_core running normally wscat test failed to connect

**Comment by dvdplm** [comment] 2021-09-18 12:08
You need to make sure to connect to the right address. In the above screenshot it looks like you're connecting to `127.0.0.1:8000` but `telemetry_core` is listening on port `8080`. Can you try again, this time ensuring the ports match up?

**Comment by woshihahaha** [comment] 2021-09-18 14:27
The front and back ends are running normally.
![image](https://user-images.githubusercontent.com/78835349/133892194-30dba568-106a-40d7-b494-c2659aa224ea.png)
There is still a problem when accessing
![Uploading image.png…]()

**Comment by dvdplm** [comment] 2021-09-20 07:47
Are you running your browser on the same machine as the telemetry frontend? If not, you need to make sure your webserver sets the `SUBSTRATE_TELEMETRY_URL` (see [`getAddress`](https://github.com/paritytech/substrate-telemetry/blob/e0ad18a5ad1869c99bd3a14807d773d86ba412c8/frontend/src/Connection.ts#L57) for details).

Also see the notes on the use of this environment variable in the [`README`](https://github.com/paritytech/substrate-telemetry/blob/e0ad18a5ad1869c99bd3a14807d773d86ba412c8/README.md#L137).

**Comment by woshihahaha** [comment] 2021-09-26 09:48
![image](https://user-images.githubusercontent.com/78835349/134802650-7d85312b-b0ba-44aa-b872-13521f19ea64.png)
The startup parameter of telemetry_core is added with -- log stace

**Comment by dvdplm** [comment] 2021-09-27 08:11
@woshihahaha I do not understand, are you asking a question?

Please try to be as detailed as possible about what it is you're trying to achieve and what your question/concern is, or this issue risks becoming a "forever thread". We are happy to help you debug any problems you might encounter with `substrate-telemetry` but we cannot assist you with general OS or networking issues. I will close this issue now, but feel free to open a new issue if you have a concrete problem we can help you with.

**Closed by dvdplm** 2021-09-27 08:11 UTC
