### ISSUE TITLE
Scrollable network tabs

### ISSUE THREAD

**Issue by xlc** [paritytech/substrate-telemetry#131] opened 2019-03-25 02:52 UTC
There are many networks available https://telemetry.polkadot.io/ and with a limited screen width, it is not possible to select the very right network.

The network tabs should be scrollable independent to the rest of the page.

**Comment by maciejhirsz** [comment] 2019-03-26 10:18
This is a duplicate of #92.

**Closed by maciejhirsz** 2019-03-26 10:18 UTC
