### ISSUE TITLE
Command "start:backend" not found

### ISSUE THREAD

**Issue by dave4you** [paritytech/substrate-telemetry#207] opened 2019-12-05 13:13 UTC
Using docker-compose up --build returns an error:
yarn run v1.19.1
error Command "start:backend" not found.

The reason is that docker-compose.yml has a reference to start:backend but it is not backed by the underlying files.

**Comment by maciejhirsz** [comment] 2019-12-05 14:52
Duplicate of #203.

**Closed by maciejhirsz** 2019-12-05 14:52 UTC
