### ISSUE TITLE
pongolin

### ISSUE THREAD

**Issue by maksim1618** [paritytech/substrate-telemetry#448] opened 2022-01-25 08:32 UTC
Uncaught error. Something went wrong with the query and rendering of this component. Please supply all the details below when logging an issue, it may help in tracing the cause.

Cannot read properties of undefined (reading 'unwrap')

TypeError: Cannot read properties of undefined (reading 'unwrap')
at https://cloudflare-ipfs.com/ipns/dotapps.io/main.1ed7d9d2.js:19:233181
at Il (https://cloudflare-ipfs.com/ipns/dotapps.io/react.01.83e78759.js:2:360831)
at t.unstable_runWithPriority (https://cloudflare-ipfs.com/ipns/dotapps.io/other.01.34ea841b.js:2:144977)
at $o (https://cloudflare-ipfs.com/ipns/dotapps.io/react.01.83e78759.js:2:301515)
at Tl (https://cloudflare-ipfs.com/ipns/dotapps.io/react.01.83e78759.js:2:360294)
at https://cloudflare-ipfs.com/ipns/dotapps.io/react.01.83e78759.js:2:360205
at R (https://cloudflare-ipfs.com/ipns/dotapps.io/other.01.34ea841b.js:2:144037)
at MessagePort.w.port1.onmessage (https://cloudflare-ipfs.com/ipns/dotapps.io/other.01.34ea841b.js:2:142760)

**Comment by jsdw** [comment] 2022-01-25 11:07
At the very least this is a duplicate of #449 so closing.

**Closed by jsdw** 2022-01-25 11:07 UTC
