### ISSUE TITLE
Port should be corrected in the frontend URL in readme.md

### ISSUE THREAD

**Issue by yayoi-k** [paritytech/substrate-telemetry#436] opened 2021-12-14 02:25 UTC
Port 8000 is the UX access port for the telemetry frontend and not 3000 as the readme states:

_With these running, you'll be able to navigate to http://localhost:**3000** to view the UI. If you'd like to connect a node and have it send telemetry to your running shard, you can run the following_

This should be corrected to read:

_With these running, you'll be able to navigate to http://localhost:**8000** to view the UI. If you'd like to connect a node and have it send telemetry to your running shard, you can run the following_

If one sets up all three containers, they will find that UX access to telemetry is not over port 3000 its over port 8000.

**Comment by dvdplm** [comment] 2021-12-14 15:30
If you run the UI locally, without Docker, the port is 3000 as stated in the readme.

The docker part of the instructions say:

```
The easiest way to run the backend and frontend images is to use docker-compose. To do this, run docker-compose up in the root of this repository to build and run the images. Once running, you can view the UI by navigating a browser to http://localhost:3000.
```

…and that could be wrong. TBF I have never used telemetry with docker so I'm actually not sure. Would you be into making a PR to fix the docs?

**Comment by jsdw** [comment] 2022-01-18 10:32
I had a quick go at this and a look at the `docker-compose` file, and `http://localhost:3000` is the correct address to access the UI for me. Looking at the raw docker steps, this also appears to be true.

There's a little confusion (for me at least) because the frontend docker image exposes things on port 8000 (which is why the compose file and suggested commands map host 3000 to guest 8000), but it all seems to work as expected.

@yayoi-k I'm going to close this for now, but if I've misunderstood something, please to re-open and provide some steps to reproduce your findings :)

**Closed by jsdw** 2022-01-18 10:32 UTC
